CREATE DATABASE library;
USE library;
CREATE TABLE books (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  author VARCHAR(100) NOT NULL,
  genre VARCHAR(100) NOT NULL,
  pages INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);